todoit/accounts/urls.py
from django.urls import path
from .views import user_login, register, home
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [

    # Temporary home
    path('', home, name='home' ),


    path("login/", user_login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path("register/", register, name="register")
]

todoit/todoapp/urls.py
from django.urls import path
from .views import index


app_name = 'todo'
urlpatterns = [
    path('', index, name="home"),
]

todoit/todoit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('todo', include('todoapp.urls')),
]

todoit/accounts/models.py
from django.db import models

# Create your models here.

todoit/todoapp/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.name
    


class ToDo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_name = models.CharField(max_length=250)
    content = models.TextField(blank=True)
    created = models.DateTimeField(default=timezone.now().strftime("%Y-%m-%d"))
    due_date = models.DateTimeField(default=timezone.now().strftime("%Y-%m-%d"))
    category = models.ForeignKey(Category, default='general',on_delete=models.CASCADE)
    tags = TaggableManager()


    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.task_name
    
    

todoit/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'form-control', 'placeholder':'Username'})
        self.fields['password'].widget.attrs.update({'class':'form-control', 'placeholder':'Password'})

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class':'form-control', 'placeholder':'Username'})
        self.fields['email'].widget.attrs.update({'class':'form-control', 'placeholder':'Email'})
        self.fields['password'].widget.attrs.update({'class':'form-control', 'placeholder':'Password'})
        self.fields['password2'].widget.attrs.update({'class':'form-control', 'placeholder':'Repeat Password'})

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

todoit/accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.

def home(request):
    return render(request, 'accounts/index.html')


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object
            new_user = user_form.save(commit=False)

            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])# encrypt the password

            # save the new user
            new_user.save()

            return render(request, 'accounts/register_done.html', {'new_user':new_user})
        
    else:
        user_form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'user_form':user_form})
        


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('todo:home')
                else:
                    messages.error(request, "Disabled account.")
                
            else:
                messages.error(request, "Invalid login attempt")

    else:
        login_form = LoginForm()
    return render(request, 'accounts/login.html', {'login_form':login_form})

todoit/todoapp/views.py
from django.shortcuts import render, redirect
from .models import ToDo, Category
from django.contrib.auth import get_user_model

# Create your views here.


def index(request):
    todos = ToDo.objects.all() #Querying all the todos with the object manager
    categories = Category.objects.all() # getting the categories with the object manager

    if request.method == 'POST':
        if "taskAdd" in request.POST:
            # checking if there is a request to add a todo
            user = request.user
            task_name = request.POST["description"] # task name
            date = str(request.POST["date"]) # date
            category = request.POST["category_select"]
            content = task_name + " -- " + date + " " + category

            Todo = ToDo(user=user, task_name=task_name, content=content, due_date=date, category=Category.objects.get(name=category))
            Todo.save()
        
        if "taskDelete" in request.POST:
            # Delete a todo
            checkedlist = request.POST["checkedbox"]
            for todo_id in checkedlist:

                print(todo_id)
                todo = ToDo.objects.get(id=int(todo_id))
                todo.delete()
    
    return render(request, "todoit/index.html", {"todos":todos, "categories":categories})
            

todoit/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}
Home page
{% endblock title %}

{% block content %}

    <div>
        <h1>Here's something.</h1>
    </div>

{% endblock content %}

todoit/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
    Todoit Log In
{% endblock title %}


{% block content %}
    {% if messages %}
        <ul>
            {% for message in messages %}
                <div class="alert alert-warning text-center alert-dismissible fade show" role="alert">
                    <strong>{{ message|safe }}</strong>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </ul>
    {% endif %}

    <h1 class="display-4 text-center text-light mt-2">Log in.</h1>

    <div class="d-flex justify-content-center p-4 mt-4">
        <form method="post">
            <div class="form-group">
                {{ login_form.username }}
            </div>
            <div class="form-group">
                {{ login_form.password }}
            </div>
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-block" value="Log In">
        
        </form>
    </div>

{% endblock content %}

todoit/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}
    Todoit SignUp
{% endblock title %}


{% block content %}
    
<h1 class="text-center display-4 text-light">Create an account.</h1>
<div class="container d-flex justify-content-center p-4">
    <form class="post-form mx-auto" method="post">
        <div class="form-group">
            {{user_form.username}}
        </div>
        <div class="form-group">
            {{user_form.email}}
        </div>
        <div class="form-group">
            {{user_form.password}}
        </div>
        <div class="form-group">
            {{user_form.password2}}
        </div>
        {% csrf_token %}
        <input class="btn btn-primary btn-block" type="submit" value="Submit">
    </form>
</div>

{% endblock content %}

todoit/accounts/templates/accounts/register_done.html
{% extends 'base.html' %}


{% block title %}
Todoit Done
{% endblock title %}

{% block content %}

<h1 class="display-4 text-light">You have been registered, {{ new_user }}!</h1>
<p>Click <a href="#">here</a> to log in.</p>

{% endblock content %}

todoit/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
    
    <title>{% block title %}Todoit{% endblock title %}</title>
</head>
<body class="bg">

    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
        <a class="navbar-brand text-light" href="#">Todoit</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            </ul>
            <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-secondary text-secondary" href="{% url 'accounts:logout' %}" aria-disabled="true">Logout</a>
                </li>
            {% else %}
                <li class="nav-item pr-2">
                    <a class="nav-link text-light" href="{% url 'accounts:register' %}" tabindex="-1" aria-disabled="true">SignUp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-secondary text-secondary" href="{% url 'accounts:login' %}" aria-disabled="true">Login</a>
                </li>
            {% endif %}


                
            </ul>
        </div>
    </nav>


    <div class="container p-4 mt-5">
        {% block content %}
        {% endblock content%}
    </div>
    
</body>
</html>

todoit/todoapp/templates/todoit/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todoit - Set your life straight.</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body class="bg">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
        <a class="navbar-brand text-light" href="#">Todoit</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            </ul>
            <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-secondary text-secondary" href="{% url 'accounts:logout' %}" aria-disabled="true">Logout</a>
                </li>
            {% else %}
                <li class="nav-item pr-2">
                    <a class="nav-link text-light" href="{% url 'accounts:register' %}" tabindex="-1" aria-disabled="true">SignUp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-secondary text-secondary" href="{% url 'accounts:login' %}" aria-disabled="true">Login</a>
                </li>
            {% endif %}


                
            </ul>
        </div>
    </nav>


    <div class="container p-4 mt-5">
        {% block content %}
        {% endblock content%}
    </div>
</body>
</html>

todoit/todoapp/templates/todoit/index.html
{% extends 'todoit/base.html' %}
{% load static %}

{% block content %}


    <div django-app="TaskManager">
        <div class="container">
            <div class="content bg-light">
                <h1 class="text-center">TodoIt App</h1>
                <p class="tagline text-center">a Django todo app</p>
                <div class="d-flex justify-content-center p-4 mt-4">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" id="description" class="form-control" placeholder="What do you need to do?" name="description" required>
                            <label for="description">Description</label>
                        </div>
                        <div class="form-group">
                            <i class="fa fa-caret-down selectArrow"></i>
                            <select name="category_select" id="category" class="form-control">
                                <option class="disabled" value="">Choose a category</option>
                                {% for category in categories %}
                                    <option class="" value="{{ category.name }}" name="{{category.name}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                            <label for="category">Category</label>
                        </div>
                        <div class="form-group">
                            <input type="date" name="date" class="form-control" id="dueDate">
                            <label for="dueDate">Due Date</label>
                        </div>
                        <div class="form-group form-inline">
                            <button class="btn btn-primary m-1" name="taskAdd" type="submit"> <img src="{% static 'bootstrap/bootstrap_icons/plus.svg' %}" alt="" srcset="" height="16" width="16"> Add task</button>
                            <button class="btn btn-danger m-1" name="taskDelete" formnovalidate="" type="submit" onclick="$('input#sublist').click();"> <img src="{% static 'bootstrap/bootstrap_icons/trash.svg' %}" width="16" height="16"> Delete Tasks</button>
                        </div>
                        <div class="form-group form-check">
                            <ul class="list-group">
                                {% for todo in todos %}
                                    <li class="list-group-item">
                                        <input type="checkbox" class="form-check-input" name="checkedbox" id="{{todo.id}}" value="{{todo.id}}">
                                        <label for="{{todo.id}}" class="form-check-label"><strong>{{ todo.task_name }}</strong></label>
                                        <span class="text-warning">{{todo.category}}</span>
                                        <span><img src="{% static 'bootstrap/bootstrap_icons/calendar-event.svg' %}" width="16" height="16"> {{todo.created}} - {{ todo.due_date }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
    


{% endblock content %}